name: Deploy IP Finder

on:
  workflow_dispatch:
  push:
    branches:
      - deployment/test-deployment

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy IP Finder
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Stop existing ip-finder process
      run: |
        pkill ip-finder || true

    - name: Build project
      run: |
        go build -o ip-finder

    - name: Execute ip-finder in background
      run: |
        nohup ./ip-finder &
